### PR TITLE
Bugfix/empty change passwords

### PR DESCRIPTION
**Pull request by markeissler**

### CODE REVIEW

**Comment by dweinand** [comment]
@markeissler @davekrupinski What needs to happen for us to close out this PR?

**Comment by davekrupinski** [comment]
@dweinand I could swear I approved this a bit ago.  Perhaps a mis-click on my end.

**Comment by markeissler** [comment]
@davekrupinski Weird. I was wondering what was happening with this.

**Comment by markeissler** [comment]
Merged via `release/1.0.8` branch and [PR#22](https://github.com/ValiMail/devise-secure_password/pull/22).

**Pull request closed without merging**
